version: '3'
services:
  myenv:
    build: .docker
    container_name: myenv
    ports:
      - "8080:8080"
    image: myenv:ubuntu
    volumes:
      # - "~/.config/nvim:/root/.config/nvim"
      - "~/work/.ghq/github.com/:/code"
      - ".docker/.bashrc:/root/.bashrc"
    tty: true
    restart: always
    # command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser
